kind: "ReplicationController"
apiVersion: "v1"
metadata:
  name: "webtest-controller"
spec:
  replicas: 1
  selector:
    app: webtest
  template:
    metadata:
      labels:
        app: webtest
    spec:
      containers:
      - name: webtest
        image: artprod.dev.bloomberg.com/bb-cto/jnegron11/webtest:latest
        ports:
        - containerPort: 8080
